spring.application.name=vehicle-data-service
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_telemetry
spring.datasource.username=nitinkumar
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
